### ISSUE TITLE
Demo app crashes with Metal SIGABRT

### ISSUE THREAD

**Issue by capnslipp** [regexident/Rainbows#2]
Demo app crashes using Xcode 15.4, running on an iPhone 14 Pro with iOS 17.6.1 with:

On line https://github.com/regexident/Rainbows/blob/82be0d7b5f06c491a55211a589bc8597b5e29511/Rainbows/GradientRenderer.swift#L204, crashes with error _Thread 1: signal SIGABRT_

In the console: _validateComputeFunctionArguments:1083: failed assertion `Compute Function(axial): argument uniforms[0] from buffer(0) with offset(0) and length(20) has space for 20 bytes, but argument has a length(24).'_

**Comment by regexident** [comment]
Thanks @capnslipp, the memory layout issues should be fixed now.
